[package]
name = "day04"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
pest = "2.7.5"
pest-ast = "0.3.4"
pest_derive = "2.7.5"
